services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      PRISM_JWT_SECRET: 4aa7e7e1-d8ca-4755-8c52-6d673a0fcd53
      PRISM_DB_PATH: /data/prism.db
      PRISM_MEDIA_DIR: /media
      PRISM_SEGMENTS_DIR: /data/segments
      PRISM_THUMBS_DIR: /data/thumbs
    ports:
      - "8080:8080"
    volumes:
      - ${MEDIA_DIR:-./dev-media}:/media:ro
      - app_data:/data

volumes:
  app_data:
