services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      GALACTIC_JWT_SECRET: 4aa7e7e1-d8ca-4755-8c52-6d673a0fcd53
      GALACTIC_DB_PATH: /data/galactic.db
      GALACTIC_MEDIA_DIR: /media
      GALACTIC_SEGMENTS_DIR: /data/segments
      GALACTIC_THUMBS_DIR: /data/thumbs
    ports:
      - "8080:8080"
    volumes:
      - ${MEDIA_DIR:-./dev-media}:/media:ro
      - app_data:/data

volumes:
  app_data:

